In [1]:
import numpy as np

In [2]:
data=np.random.randint(0,20,(5,5))

In [3]:
data

array([[12,  0, 18, 12,  9],
       [17, 15, 19, 11,  3],
       [ 8, 15,  7, 12, 19],
       [ 0,  4,  5,  1,  6],
       [17,  2,  4,  9, 11]])

In [4]:
data.sum()

np.int64(236)

In [5]:
data.sum(axis=1)

array([51, 65, 61, 16, 43])

In [6]:
data.sum(axis=0)

array([54, 36, 53, 45, 48])

In [7]:
data.max()

np.int64(19)

In [8]:
data.min()

np.int64(0)

In [9]:
data.max(axis=1)

array([18, 19, 19,  6, 17])

In [10]:
data.min(axis=0)

array([0, 0, 4, 1, 3])

In [11]:
data.max(axis=0)

array([17, 15, 19, 12, 19])

In [12]:
data.min(axis=1)

array([0, 3, 7, 0, 2])

In [13]:
data.argmax(axis=1)

array([2, 2, 4, 4, 0])

In [14]:
data.argmin(axis=1)

array([1, 4, 2, 0, 1])

In [15]:
data.argmax(axis=0)

array([1, 1, 1, 0, 2])

In [16]:
data.argmin(axis=0)

array([3, 0, 4, 3, 1])

In [59]:
data=np.random.randint(10,50,(3,5))

In [61]:
data

array([[26, 34, 18, 16, 25],
       [28, 38, 41, 42, 40],
       [42, 33, 11, 29, 24]])

In [62]:
data.sum()

np.int64(447)

In [63]:
data.max(axis=1)

array([34, 42, 42])

In [66]:
data.min(axis=1)

array([16, 28, 11])

In [65]:
data.sum(axis=1)

array([119, 189, 139])

In [67]:
data.sum(axis=1).argmax()+1

np.int64(2)

In [68]:
data.sum(axis=1).argmin()+1

np.int64(1)

In [69]:
data.sum(axis=0)

array([ 96, 105,  70,  87,  89])

In [70]:
data.sum(axis=0).argmax()+1

np.int64(2)

In [71]:
data.sum(axis=0).argmin()+1

np.int64(3)

In [75]:
data.sum(axis=0)[3:].sum()

np.int64(176)

In [76]:
data[:,3:5].sum()

np.int64(176)

In [77]:
data

array([[26, 34, 18, 16, 25],
       [28, 38, 41, 42, 40],
       [42, 33, 11, 29, 24]])

In [78]:
data.sum(axis=0).max()

np.int64(105)

In [79]:
data.sum(axis=0).min()

np.int64(70)

In [80]:
data.sum(axis=0).max()-data.sum(axis=0).min()

np.int64(35)

In [83]:
data=np.random.randint(0,20,10)

In [84]:
data

array([ 1,  9,  5,  9,  1,  8,  9,  4, 13,  4])

In [86]:
data.mean()

np.float64(6.3)

In [89]:
np.median(data)

np.float64(6.5)

In [90]:
np.quantile(data,0.25)

np.float64(4.0)

In [91]:
np.quantile(data,0.75)

np.float64(9.0)

In [92]:
np.quantile(data,0.50)


np.float64(6.5)

In [93]:
np.std(data)

np.float64(3.716180835212409)

In [94]:
np.var(data)

np.float64(13.809999999999999)

In [95]:
data=np.random.randint(0,10,(10,2))

In [96]:
data

array([[9, 1],
       [1, 5],
       [2, 2],
       [9, 6],
       [1, 9],
       [9, 9],
       [4, 6],
       [9, 0],
       [1, 1],
       [7, 7]])

In [97]:
np.corrcoef(data.T)

array([[ 1.        , -0.02821663],
       [-0.02821663,  1.        ]])

In [98]:
v1=np.arange(1,11)

In [99]:
v2=np.arange(10,20)

In [100]:
x=[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
x.reverse()
v2=np.array(x)
v2

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [102]:

data[:,0]=v1
data[:,1]=v2

In [103]:
np.corrcoef(data.T)

array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
### Descriptive Statistics
mean
median
max
min
range
q1
q3
iqr
std
var
