In [ ]:
import numpy as np

In [ ]:
list(),str(),tuple(),set(),dict()

([], '', (), set(), {})

In [ ]:
y=np.array([1,2,3])

In [ ]:
x=[1,2,3]

In [ ]:
type(x),type(y)

(list, numpy.ndarray)

In [ ]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
y/2

array([0.5, 1. , 1.5])

In [ ]:
x=[1,2,3,"data "]

In [ ]:
x

[1, 2, 3, 'data ']

In [ ]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(int, int, int, str)

In [ ]:
y=np.array([1,2,3,3.6,"data"])

In [ ]:
type(y[0]),type(y[1]),type(y[2]),type(y[3])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [ ]:
y

array(['1', '2', '3', '3.6', 'data'], dtype='<U32')

In [ ]:
for i in range(1,10):
  print(np.random.randint(0,5))

3
1
1
0
0
2
4
4
1


In [ ]:
p.random.randint(0,10,(5,5))

array([[7, 6, 8, 7, 9],
       [0, 5, 9, 5, 0],
       [1, 0, 7, 2, 1],
       [7, 7, 6, 5, 7],
       [1, 1, 9, 2, 7]])

In [ ]:
data=np.random.randint(0,50,(5,5))

In [ ]:
data

array([[24, 14, 29,  4, 24],
       [25, 10,  9, 39, 19],
       [ 1, 16, 36,  7, 11],
       [30, 18, 10, 43, 10],
       [36, 48, 42, 35, 27]])

In [ ]:
data[0:3,4:5]

array([[24],
       [19],
       [11]])

In [ ]:
data[-5:-3,-5:-4]

array([[24],
       [25]])

In [ ]:
data[-4:-2,-3:-2]

array([[ 9],
       [36]])

In [ ]:
data[-3:-1,-3:-1]

array([[36,  7],
       [10, 43]])

In [ ]:
data[0,:]

array([24, 14, 29,  4, 24])

In [ ]:
data[:,0]

array([24, 25,  1, 30, 36])

In [ ]:
data[:]

array([[24, 14, 29,  4, 24],
       [25, 10,  9, 39, 19],
       [ 1, 16, 36,  7, 11],
       [30, 18, 10, 43, 10],
       [36, 48, 42, 35, 27]])

In [ ]:
data.shape

(5, 5)

In [ ]:
data.size

25

In [ ]:
data.T

array([[24, 25,  1, 30, 36],
       [14, 10, 16, 18, 48],
       [29,  9, 36, 10, 42],
       [ 4, 39,  7, 43, 35],
       [24, 19, 11, 10, 27]])

In [ ]:
data

array([[24, 14, 29,  4, 24],
       [25, 10,  9, 39, 19],
       [ 1, 16, 36,  7, 11],
       [30, 18, 10, 43, 10],
       [36, 48, 42, 35, 27]])

In [ ]:
data

array([[24, 14, 29,  4, 24],
       [25, 10,  9, 39, 19],
       [ 1, 16, 36,  7, 11],
       [30, 18, 10, 43, 10],
       [36, 48, 42, 35, 27]])

In [ ]:
x=2

In [ ]:
data**2

array([[ 4,  9,  9,  1,  4],
       [ 1, 16,  0,  1,  0],
       [ 0,  1,  4,  4,  9]])

In [ ]:
x=np.random.randint(0,5,(5,5))
y=np.random.randint(0,7,(3,3))

In [ ]:
x

array([[1, 2, 4, 0, 0],
       [3, 3, 0, 0, 0],
       [2, 0, 0, 1, 1],
       [2, 3, 3, 3, 3],
       [3, 0, 4, 4, 4]])

In [ ]:
y

array([[6, 1, 3],
       [1, 5, 1],
       [3, 4, 6]])

In [ ]:
np.add(x,5)

array([[6, 7, 9, 5, 5],
       [8, 8, 5, 5, 5],
       [7, 5, 5, 6, 6],
       [7, 8, 8, 8, 8],
       [8, 5, 9, 9, 9]])

In [ ]:
np.multiply(x,4)

array([[ 4,  8, 16,  0,  0],
       [12, 12,  0,  0,  0],
       [ 8,  0,  0,  4,  4],
       [ 8, 12, 12, 12, 12],
       [12,  0, 16, 16, 16]])

In [ ]:
np.divide(x,2)

array([[0.5, 1. , 2. , 0. , 0. ],
       [1.5, 1.5, 0. , 0. , 0. ],
       [1. , 0. , 0. , 0.5, 0.5],
       [1. , 1.5, 1.5, 1.5, 1.5],
       [1.5, 0. , 2. , 2. , 2. ]])

In [ ]:
np.floor_divide(x,2)

array([[0, 1, 2, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 0, 2, 2, 2]])

In [ ]:
np.exp(x)

array([[ 2.71828183,  7.3890561 , 54.59815003,  1.        ,  1.        ],
       [20.08553692, 20.08553692,  1.        ,  1.        ,  1.        ],
       [ 7.3890561 ,  1.        ,  1.        ,  2.71828183,  2.71828183],
       [ 7.3890561 , 20.08553692, 20.08553692, 20.08553692, 20.08553692],
       [20.08553692,  1.        , 54.59815003, 54.59815003, 54.59815003]])

In [ ]:
np.pow(x,2)

array([[ 1,  4, 16,  0,  0],
       [ 9,  9,  0,  0,  0],
       [ 4,  0,  0,  1,  1],
       [ 4,  9,  9,  9,  9],
       [ 9,  0, 16, 16, 16]])

In [ ]:
np.random.rand(3,5)

array([[0.79450033, 0.60517266, 0.30274095, 0.52472756, 0.32369304],
       [0.23141957, 0.35360806, 0.51646886, 0.33035208, 0.79267689],
       [0.91938028, 0.58716029, 0.93290762, 0.45333938, 0.89570863]])

In [ ]:
np.random.randn(1300,1300).std()

np.float64(0.9998387748228741)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
data=np.random.randint(0,5,(3,5))

In [ ]:
data

array([[2, 3, 3, 1, 2],
       [1, 4, 0, 1, 0],
       [0, 1, 2, 2, 3]])

In [ ]:
print(data.sum())
print(data.min())
print(data.max())

25
0
4


In [ ]:
data.argmax()

np.int64(6)

In [ ]:
data=np.random.randint(0,10,(5,5))

In [ ]:
data

array([[2, 9, 2, 7, 0],
       [3, 2, 2, 6, 7],
       [0, 9, 6, 9, 6],
       [4, 4, 1, 0, 1],
       [8, 7, 8, 3, 5]])

In [ ]:
data.sum(axis=1)

array([20, 20, 30, 10, 31])

In [ ]:
data.sum(axis=0)

array([17, 31, 19, 25, 19])

In [ ]:
data

array([[2, 9, 2, 7, 0],
       [3, 2, 2, 6, 7],
       [0, 9, 6, 9, 6],
       [4, 4, 1, 0, 1],
       [8, 7, 8, 3, 5]])

In [ ]:
data.argmin(axis=1)

array([4, 1, 0, 3, 3])

In [ ]:
data.argmax(axis=0)

array([4, 0, 4, 2, 1])

In [ ]:
data.argmin(axis=0)

array([2, 1, 3, 3, 0])

In [ ]:
data.argmax(axis=1)

array([1, 4, 1, 0, 0])